### CMSC 197 (Machine Learning) - Quiz 1
##### by Hismaña, Nikko Gabriel (2009-48594)

PREREQ: Initializing Numpy

In [17]:
import numpy as np

## PART 1: 

1. Create 2 1D arrays, y_hat and y
2. initialize y_hat with 20 linearly spaced numbers between -1 and 1

In [18]:
#where np.linspace(start, stop, number of values)
y_hat = np.linspace(-1, 1, 20)  
#checking the content of y_hat
print(y_hat)

[-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]


3. Initialize y with 20 linearly spaced numbers between 0 and 1

In [19]:
#where np.linspace(start, stop, number of values)
y = np.linspace(0, 1, 20) 
#checking the content of y
print(y)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


4. Compute for the shape and dimension of y_hat and y

In [20]:
# y_hat shape and dimensions
print("y_hat")
print(f"y_hat shape: {y_hat.shape}")
print(f"y_hat dimension: {y_hat.ndim}\n")
# y shape and dimensions
print("y")
print(f"y shape: {y.shape}")
print(f"y dimension: {y.ndim}")


y_hat
y_hat shape: (20,)
y_hat dimension: 1

y
y shape: (20,)
y dimension: 1


5. Create individual functions for each of the loss functions with y and y_hat as parameters
6. Each function should return the loss value (L) 

### <header style=color:skyblue>Mean Squared Error (MSE):</p>

In [21]:
# function defining mean squared error:
def mse(y_hat, y):
    #L = loss value
    #use np.mean() to calculate the mean of the squared diff bet y_hat and y
    L = np.mean((y_hat - y)**2)
    return L 
    
#running the mse function to get L:
print(f"MSE loss value (L): {mse(y_hat, y)}")

MSE loss value (L): 0.3421052631578948


### <header style=color:magenta>Mean Absolute Error (MAE):</p>

In [22]:
# function defining mean absolute error:
def mae(y_hat, y):
    #L = loss value
    #use np.abs() to get absolute value
    L = np.mean(np.abs(y_hat - y))
    return L
    
#running the mae function to get L:
print(f"MAE loss value (L): {mae(y_hat, y)}")

MAE loss value (L): 0.4999999999999999


### <header style=color:lightgreen>Mean Squared Logarithmic Error (MSLE):</p>

In [23]:
# function defining mean squared logaritmic error:
def msle(y_hat, y):
    #L = loss value
    #use np.log() to get logaritmic value of y_hat +1 and y+1 squared
    L = np.mean((np.log(y_hat + 1) - np.log(y + 1))**2)
    if L == np.inf:
        return "Loss value cannot be calculated, division by zero"
    return L
    
#running the msle function to get L:
print(f"MSLE loss value (L): {msle(y_hat, y)}")

MSLE loss value (L): Loss value cannot be calculated, division by zero


C:\Users\asus\AppData\Local\Temp\ipykernel_20608\1663691818.py:5: RuntimeWarning: divide by zero encountered in log
  L = np.mean((np.log(y_hat + 1) - np.log(y + 1))**2)


##### <p style=color:red> Note: For this example, MSLE function will result in an error due to dividing by zero </p>

### <header style=color:yellow>Mean Absolute Percentage Error (MAPE):</p>

In [24]:
# function defining mean absolute percentage error:
def mape(y_hat, y):
    #L = loss value
    #use np.abs() to get absolute value of y_hat - y divided by y
    L = np.mean(np.abs((y_hat - y)/y))
    if L == np.inf:
        return "Loss value cannot be calculated, division by zero"
    return L

#running the mape function to get L:
print(f"MAPE loss value (L): {mape(y_hat, y)}")

MAPE loss value (L): Loss value cannot be calculated, division by zero


C:\Users\asus\AppData\Local\Temp\ipykernel_20608\1562451304.py:5: RuntimeWarning: divide by zero encountered in divide
  L = np.mean(np.abs((y_hat - y)/y))


##### <p style=color:red> Note: For this example, MAPE function will result in an error due to dividing by zero </p>

## PART 2: 

1. Create a 1d array M {1, 2, …16} using the arange function

In [25]:
#arange method: np.arange(start, stop, step)
M = np.arange(1, 17, 1)
#check contents of M
print(M)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


2. Reshape M into 4x4 array and store it to N

In [26]:
#numpy reshape function: N.reshape(row, column)
N = M.reshape(4, 4)
#check contents of N matrix:
print(N)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


3. Get the 2nd row of N

In [27]:
#get the 2nd row of N matrix:
print(f"second row values: {N[1]}") #recall that indexing starts from 0, so 1 is the 2nd row

second row values: [5 6 7 8]


4. Get the minimum values for each column of N

In [28]:
#store the minimum values for each column of N using np.min() function:
min_col = np.min(N, axis=0)

#print out the min_N values:
for i in range(len(min_col)):
    print(f"Minimum value for column {i}: {min_col[i]}")

Minimum value for column 0: 1
Minimum value for column 1: 2
Minimum value for column 2: 3
Minimum value for column 3: 4


5. Get the locations of the minimum values for each column of N

In [29]:
#use np.where method to get the coordinate of the minimum value for each column of N:
#np.where returns a tuple of arrays:
# first array contains the row numbers 
# second array contains the column numbers
min_col_index = np.where(N == min_col)

#print out the coordinate of the min_N values per column:
for i in range(len(min_col)):
    # min_col_index[0][i] is the row coordinate of the min val for the i-th column
    # min_col_index[1][i] is the column coordinate of the min val for the i-th column
    print(f"Minimum value for column {i} is {min_col[i]} at coordinate: {min_col_index[0][i], min_col_index[1][i]}")

Minimum value for column 0 is 1 at coordinate: (0, 0)
Minimum value for column 1 is 2 at coordinate: (0, 1)
Minimum value for column 2 is 3 at coordinate: (0, 2)
Minimum value for column 3 is 4 at coordinate: (0, 3)


6. Get the average of the whole matrix

In [30]:
#use np.mean() method to compute for the average of the whole matrix N:
avg_N = np.mean(N)
#print out the avg_N value:
print(f"Average value of N: {avg_N}")

Average value of N: 8.5


7. Create a vector V with 4 elements, each element is 1

In [31]:
#use np.ones method to create a matrix with 1s as value:
#where np.ones((row,col), dtype= type of value)
V = np.ones(4, dtype=int)
#check contents of V:
print(f"Vector V has contents: {V}")

Vector V has contents: [1 1 1 1]


8. Take the dot product of N and V

In [32]:
#use np.dot method to compute for the dot product of N and V:
dot_prod = np.dot(N, V)
#check contents of dot_prod:
print(f"Dot product of matrix N and vector V: {dot_prod}")


Dot product of matrix N and vector V: [10 26 42 58]


# ========= END OF QUIZ =========